FROM python:3.12.3

WORKDIR /var/www/app

RUN pip install --upgrade pip

COPY python/app/* /var/www/app

RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
